# Generated by Django 3.2.5 on 2021-08-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('feedback', models.TextField(max_length=12222)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
